# Generated by Django 4.2.4 on 2023-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_registro_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='provincias',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
