# Generated by Django 4.2.4 on 2023-09-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registro_provincias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='orden_bolsa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_bolsa',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
