# Generated by Django 4.2.4 on 2023-12-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_categoria_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(blank=True),
        ),
    ]
