# Generated by Django 4.2.4 on 2023-12-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=255),
        ),
    ]
