# Generated by Django 4.2.4 on 2023-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_version_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
