# Generated by Django 4.2.4 on 2023-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_version_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(default='slug-slug', max_length=255),
        ),
    ]
