# Generated by Django 4.2.4 on 2024-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_noticia_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(default='prueba', max_length=255),
            preserve_default=False,
        ),
    ]
