# Generated by Django 4.2.4 on 2024-01-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_categoria_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='mostrar_imagen',
            field=models.BooleanField(default=False),
        ),
    ]
