# Generated by Django 4.2.4 on 2024-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_noticia_mostrar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerpo',
            name='imagen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='imagen',
            field=models.TextField(blank=True),
        ),
    ]
