# Generated by Django 4.2.4 on 2024-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cuerpo_imagen_especialidad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
