# Generated by Django 4.2.4 on 2024-03-09 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_centro_programa_plaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaza',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.programa'),
        ),
    ]
