# Generated by Django 4.2.4 on 2024-03-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='centro',
            options={'verbose_name': 'Centro', 'verbose_name_plural': 'Centros'},
        ),
        migrations.AlterModelOptions(
            name='cuerpo',
            options={'ordering': ['codigo'], 'verbose_name': 'Cuerpo', 'verbose_name_plural': 'Cuerpos'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['codigo'], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='funcion',
            options={'verbose_name': 'Función', 'verbose_name_plural': 'Funciones'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['id'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='plaza',
            options={'verbose_name': 'Plaza', 'verbose_name_plural': 'Plazas'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['codigo'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Versión', 'verbose_name_plural': 'Versiones'},
        ),
        migrations.AddField(
            model_name='centro',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.provincia'),
        ),
    ]
