# Generated by Django 4.2.4 on 2024-08-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_categoria_options_alter_centro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.especialidad')),
            ],
            options={
                'verbose_name': 'Tipo de Acceso',
                'verbose_name_plural': 'Tipos de Acceso',
            },
        ),
        migrations.CreateModel(
            name='RegistroBolsaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('dni', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('apellidos', models.CharField(blank=True, max_length=255)),
                ('orden_bolsa', models.CharField(blank=True, max_length=255)),
                ('puntos', models.DecimalField(decimal_places=4, max_digits=6)),
                ('puntos_ado1_experiencia', models.DecimalField(decimal_places=4, max_digits=5)),
                ('puntos_ado2_examen', models.DecimalField(decimal_places=4, max_digits=5)),
                ('puntos_ado3_formacion', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tipo_bolsa', models.CharField(blank=True, max_length=255)),
                ('ingles', models.BooleanField()),
                ('frances', models.BooleanField()),
                ('aleman', models.BooleanField()),
                ('italiano', models.BooleanField()),
                ('lengua_signos', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.acceso')),
                ('especialidades', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.especialidad')),
            ],
            options={
                'verbose_name': 'Registro Bolsa General',
                'verbose_name_plural': 'Registros Bolsa General',
            },
        ),
    ]
