# Generated by Django 4.2.4 on 2025-02-27 13:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_acceso_registrobolsageneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
