# Generated by Django 4.2.4 on 2025-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_centro_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
    ]
