# Generated by Django 4.2.4 on 2025-07-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_registro_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centro',
            name='coordinates',
        ),
    ]
