# Generated by Django 4.2.4 on 2025-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_centro_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='adjudicado',
            field=models.BooleanField(default=False),
        ),
    ]
