# Generated by Django 4.2.4 on 2025-07-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_registro_adjudicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='orden',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
