# Generated by Django 4.2.4 on 2025-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_registro_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
