# Generated by Django 4.2.4 on 2025-08-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_registro_apellidos_alter_registro_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaza',
            name='id_plaza',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
