# Generated by Django 4.2.4 on 2025-08-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_plaza_id_plaza'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaza',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
