# Generated by Django 4.2.4 on 2025-08-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_plaza_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaza',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='plaza',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
