# Generated by Django 4.2.4 on 2025-08-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_plaza_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='plaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.plaza'),
        ),
    ]
