# Generated by Django 4.2.4 on 2025-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_registro_plaza'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
