# Generated by Django 4.2.4 on 2025-08-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_centro_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuerpo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='imagen',
        ),
    ]
