# Generated by Django 4.2.4 on 2025-08-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_cuerpo_imagen_remove_especialidad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='movil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
