# Generated by Django 4.2.4 on 2025-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_centro_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrobolsageneral',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
