# Generated by Django 4.2.4 on 2025-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_registrobolsageneral_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
