# Generated by Django 4.2.4 on 2025-09-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_provincia_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='color',
        ),
    ]
